#!/usr/bin/env bash
# One-time provisioning for a fresh Ubuntu droplet.
#
#   ssh root@YOUR_DROPLET_IP
#   curl -fsSL https://raw.githubusercontent.com/Innovagrow/procurement-dash-factory/claude/upwork-detection-bidding-0k08ry/upwork-autobid/deploy/setup-droplet.sh -o setup.sh
#   bash setup.sh yourdomain.com
#
# Idempotent: safe to re-run.
set -euo pipefail

DOMAIN="${1:-}"
APP_DIR=/opt/upbid
REPO=https://github.com/Innovagrow/procurement-dash-factory.git
BRANCH=claude/upwork-detection-bidding-0k08ry

echo "==> Installing Docker and dependencies"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq ca-certificates curl git ufw >/dev/null

if ! command -v docker >/dev/null 2>&1; then
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  chmod a+r /etc/apt/keyrings/docker.asc
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin >/dev/null
fi
systemctl enable --now docker

echo "==> Firewall"
ufw allow OpenSSH >/dev/null
ufw allow 80/tcp   >/dev/null
ufw allow 443/tcp  >/dev/null
ufw --force enable >/dev/null

echo "==> Fetching the application"
if [ -d "$APP_DIR/.git" ]; then
  git -C "$APP_DIR" fetch origin "$BRANCH" --depth 1
  git -C "$APP_DIR" checkout -B "$BRANCH" "origin/$BRANCH"
else
  git clone --depth 1 --branch "$BRANCH" "$REPO" "$APP_DIR"
fi

cd "$APP_DIR/upwork-autobid"

if [ ! -f .env ]; then
  echo "==> Creating .env with generated secrets"
  API_KEY=$(openssl rand -hex 24)
  PG_PASSWORD=$(openssl rand -hex 16)
  cp .env.example .env
  sed -i "s|^API_KEY=.*|API_KEY=\"$API_KEY\"|" .env
  {
    echo ""
    echo "# --- generated by setup-droplet.sh ---"
    echo "POSTGRES_PASSWORD=\"$PG_PASSWORD\""
    echo "DATABASE_URL=\"postgresql://upbid:$PG_PASSWORD@postgres:5432/upbid\""
    echo "REDIS_URL=\"redis://redis:6379\""
    echo "NODE_ENV=\"production\""
    echo "DRY_RUN=\"true\""
    echo "AUTO_SUBMIT=\"false\""
    [ -n "$DOMAIN" ] && echo "PUBLIC_BASE_URL=\"https://$DOMAIN\""
  } >> .env
  echo ""
  echo "    Dashboard API key: $API_KEY"
  echo "    (saved in $APP_DIR/upwork-autobid/.env — you need it to log in)"
  echo ""
else
  echo "==> .env already exists, leaving it alone"
fi

if [ -n "$DOMAIN" ]; then
  echo "==> Configuring Caddy for https://$DOMAIN"
  sed -i "s|__DOMAIN__|$DOMAIN|" deploy/Caddyfile 2>/dev/null || true
  COMPOSE_FILES="-f docker-compose.yml -f deploy/docker-compose.caddy.yml"
else
  echo "==> No domain given — serving plain HTTP on port 3000"
  COMPOSE_FILES="-f docker-compose.yml"
fi

echo "==> Building and starting"
# shellcheck disable=SC2086
docker compose $COMPOSE_FILES up -d --build

echo "==> Installing auto-update timer (pulls and redeploys every 10 minutes)"
cat > /etc/systemd/system/upbid-update.service <<UNIT
[Unit]
Description=Pull and redeploy UpBid
After=docker.service

[Service]
Type=oneshot
WorkingDirectory=$APP_DIR/upwork-autobid
ExecStart=/usr/bin/git -C $APP_DIR fetch origin $BRANCH --depth 1
ExecStart=/usr/bin/git -C $APP_DIR reset --hard origin/$BRANCH
ExecStart=/usr/bin/docker compose $COMPOSE_FILES up -d --build
UNIT

cat > /etc/systemd/system/upbid-update.timer <<UNIT
[Unit]
Description=Redeploy UpBid periodically

[Timer]
OnBootSec=5min
OnUnitActiveSec=10min

[Install]
WantedBy=timers.target
UNIT

systemctl daemon-reload
systemctl enable --now upbid-update.timer

echo ""
echo "==> Done."
if [ -n "$DOMAIN" ]; then
  echo "    Dashboard: https://$DOMAIN"
else
  echo "    Dashboard: http://$(curl -fsS4 ifconfig.me 2>/dev/null || echo YOUR_IP):3000"
fi
echo "    Logs:      cd $APP_DIR/upwork-autobid && docker compose logs -f worker"
echo "    API key:   grep API_KEY $APP_DIR/upwork-autobid/.env"
echo ""
echo "    Next: edit .env to add ANTHROPIC_API_KEY, IMAP_* and TELEGRAM_*, then"
echo "          docker compose $COMPOSE_FILES up -d"
